bucket.go
table.go
table_test.go
util.go

`commonPrefixLen` is useful outside the package, for example [here](https://github.com/anacrolix/go-libp2p-dht-tool/blob/ad36b4be13b82f02a837d46667f3d276430d435c/main.go#L191).

Export CommonPrefixLen

---

bucket.go
table.go

PeerRemoved was called even when the peer wasn't in the routing table. This was generating bogus routing table churn metrics.

Only call PeerRemoved when the peer was just removed

---

sorting.go

the builtin function `copy` will use  the minimum of len(src) and len(dst).  so this code use zero length for newArr will not copy the peerArr content.

fix: copyPeersFromList may cause peerArr be empty

---

sorting.go
table.go

I tidied up some ambiguous behaviours after https://github.com/libp2p/go-libp2p-kbucket/pull/29. In particular there's some manual copying that isn't necessary, and the user of `[]*peerDistance` when `[]peerDistance` will suffice (and the last change here was an attempt to reduce allocations). Copying is replaced with append to make it clear about how to preallocate, and that the slice can/will be modified in place per normal append semantics.
I see that with unusual `count` values given to `NearestPeers`, behaviour isn't optimal, but I'm guessing that's not come up as count is likely `KValue` which is approximately the bucket size most of the time.
`SortClosestPeers` isn't used anywhere that I can see. I wonder if it should even be in this repo.

Remove a lot of allocations, and fix some ambiguous naming

---

go.mod
keyspace/xor.go
util.go

This is the one we're using in secio/multihash.

dep: use a faster sha256 library

---

table.go
table_test.go

Processing _all_ the buckets to the right isn't worth it. Unfortunately, testing this was a real pain.

feat: approximate closer peers instead of being exact

---

go.mod
table.go
table_test.go

The neighbors may _also_ be empty or low. This can cause peers with a low number of peers in their routing table to fail to find _any_ peers in their routing table.

fix: when the target bucket is empty or low, pull from all other buckets

---

bucket.go
table.go
table_test.go

@Stebalien 
For  https://github.com/libp2p/go-libp2p-kad-dht/issues/406
Please review.

Refresh Cpl's, not buckets

---

bucket.go
cpl_replacement_cache.go
cpl_replacement_cache_test.go
go.mod
go.sum
options.go
sorting.go
table.go
table_test.go

@raulk @Stebalien @aschmahmann @dirkmc 
For https://github.com/libp2p/go-libp2p-kad-dht/issues/283
**1.** Address management is not a part of this PR & will be next.
**2.** DHT changes will be made once this goes in.
**3.** IMO, moving the RT inside `go-libp2p-kad-dht` is a bigger refactoring that will involve multiple discussions and should be done as a separate stream of work.

Disassociate RT membership from connectivity

---

bucket.go
sorting.go
table.go
table_test.go

@Stebalien @aschmahmann 
For https://github.com/libp2p/go-libp2p/issues/812 AND https://github.com/libp2p/go-libp2p-kbucket/pull/64.
Saves us from having to do repeated SHA's.

Cache the XOR DHT Id for a peerID

---

table.go
table_test.go

This reverts an optimization where we fudged the closer peers when returning responses to users when we were within a power of two to the target.

fix: use accurate bucket logic

---

bucket.go
sorting.go
table.go
table_test.go

For https://github.com/libp2p/go-libp2p-kad-dht/issues/521.

Get Peer Infos

---

bucket.go
table.go
table_refresh.go
table_refresh_test.go

To determine how many buckets we should refresh, we:
1. Look at the max bucket.
2. Look at the peer with the greatest common prefix in the max bucket.
3. Return the "last refresh" times for all buckets between 0 and `min(maxPeer, 15)`
BREAKING: this returns a slice of times instead of CplRefresh objects because we want to refresh _all_ buckets between 0 and the max CPL.

fix: correctly track CPLs of never refreshed buckets

---

bucket.go
go.mod
table.go
table_test.go

`LastUsefulAt` helps evict peers that aren't being useful.
`LastSuccessfulQueryAt` decides which peers we ping periodically to check liveliness.

Add LastUsefulAt and LastSuccessfulQueryAt for each peer

---

table.go
table_test.go

In meta-issue  https://github.com/libp2p/go-libp2p-kad-dht/issues/556,  this if for: 
* https://github.com/libp2p/go-libp2p-kad-dht/issues/550
* In order to know when to stop refreshing a CPL, we first need to know the peers we have for a given CPL.
* https://github.com/libp2p/go-libp2p-kbucket/issues/72
* We should collapse  the last/second last bucket if it's empty.

NPeersForCpl and collapse empty buckets

---

bucket.go
bucket_test.go
table.go
table_test.go

@Stebalien 
For https://github.com/libp2p/go-libp2p-kad-dht/issues/594.

Reduce allocs in AddPeer

---

bucket.go
table.go
table_test.go

I'd like to use this in an IPFS dht stat command.

feat: add an AddedAt timestamp

---

table.go
table_test.go

@Stebalien 
This is the fix for the bug wherein we don't fire `PeerRemoved` notifications when we replace "less useful" peers in a bucket.
Given that we are now going to unprotect peers when we get the peer removed notification from kbucket, this is important to land.

Fix bug in peer eviction

---

bucket.go
bucket_test.go
table.go
table_refresh_test.go
table_test.go

For https://github.com/libp2p/go-libp2p-kad-dht/issues/661.

Reduce Routing Table churn

---

peerdiversity/filter.go

Currently when an ASN cannot be found for an IPv6 address the diversity filter will reject the peer. In this PR we fallback to using the /32 mask of the IP address as the group ID.
@aarshkshah1992 @willscott @Stebalien

ipv6 diversity: when asn not found fallback to /32 mask

---

table.go
table_test.go

I just added a test called TestBugFinder which fails because when adding a new peer to a bucket in which another peer will be evicted to make space for the new one (having the bucketsize = 1), the code just doesn't take into account that the bucket where the new peer info is going to be added may be deleted from the routing table. 
I just added lines that take care of it.  I know the test is very specific and that the probability of the bucketsize being equals to 1 is very little, but when someone uses the code she/he usually assumes it will work just fine.

fixed kbucket bug :)

---

table.go
table_test.go

UsefulPeer verifies whether a given peer.ID would be a good fit for the routing table. It returns true if the bucket corresponding to peer.ID isn't full, if it contains replaceable peers or if it is the last bucket and adding a peer would unfold it.
This function is necessary for [go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht), as remote DHT servers are queried before they are added to the DHT. We don't want to query peers whose ID belong to a full bucket anyway. This function helps preventing querying useless peers.
References: https://github.com/libp2p/go-libp2p-kad-dht/pull/820

UsefulPeer function

---

go.mod
go.sum
table.go
table_test.go

A peer should be considered as useful for the routing table if it isn't already in the routing table.
Renamed `UsefulPeer()` to `UsefulNewPeer()`, and added a check to verify if the peer is already in the routing table.
See https://github.com/libp2p/go-libp2p-kad-dht/commit/d373974d31867207c5ce3b471f1d8c0fb5f14e05#r117905977

Replacing UsefulPeer() with UsefulNewPeer()

---

table.go
version.json

This fixes a deadlock the issue is that this pattern could happen because .Find inside UsefullNewPeer would aquire the same RLock:
- UsefullNewPeer takes tablock.RLock
- Something else tries to take tablock.Lock (waits)
- UsefullNewPeer calls Find calls NearestPeer call NearestPeers which trie to take tablock.RLock again, here RLock waits because the rwmutex is starving, it will wait for the Something else to aqcuire the Lock first else a constant flow of reader would block the RWMutex forever.

fix: fix abba bug in UsefullNewPeer

---

table.go

As of now, I don't think there is a major log in Kademlia that *certainly* can determine that a peer has been added.
The login `'msg': 'peer found'` output, which is called prior to the commit, is only an possibility to add for the peer, and the fact that `'rt.PeerAdd()'`, which is actually called when a peer is added, is an empty function makes it difficult to measure the performance of Kademlia.
```go
PeerRemoved: func(p peer.ID) {
log.Debugw("peer removed", "peer", p)
},
PeerAdded: func(p peer.ID) {
log.Debugw("peer added", "peer", p)
},
```
Thus, a simple log-add syntax was added.

feat: add log printing when peer added and removed table
